### PR TITLE
Ported to Kodi 19

### PR DESCRIPTION
**Pull request by mkaflowski**
- ported to python 3
- added margins to icon
- added localized strings
- adjusted to Kodi team requirements

### CODE REVIEW

**Comment by ciukacz** [comment]
throws an exception when path is a SMB share:

Error Type: <class 'OSError'>
Error Contents: [Errno 22] Invalid argument: 'smb://htpc2/movies2/hdr/Aquaman.2018.MULTi.2160p.UHD.BluRay.HEVC-PTRG/Aquaman.2018.MULTi.2160p.UHD.BluRay.HEVC-PTRG.mkv'

**Comment by mkaflowski** [comment]
I used wrong function for file reading. It should be fixed now.

**Comment by CaTzil** [comment]
Thank u for the effort 🙏🏼, but looks like I've managed to make a smaller change in order to support Kodi 19

**Comment by mkaflowski** [comment]
Great! Will you add it to official Kodi repo soon?

**Comment by CaTzil** [comment]
I've made the PR, ot waiting for approval.

**Pull request closed without merging**
